const jobListData=[
    {
        id: 1,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png",
        category: "WebDev",
        role: "React Developer",
        company: "GlobalLogic Private Limited",
        location: "Banglore",
        experience: "0+years",
    },
    {
        id: 2,
        image: "https://repository-images.githubusercontent.com/24195339/87018c00-694b-11e9-8b5f-c34826306d36",
        category: "WebDev",
        role: "Angular Developer",
        company: "Morgan Stanely",
        location:"Pune",
        experience: "2+years",
    },
    {
        id: 3,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX4Cmg9Qqr40B_M1GqLhOP85blH6ucwbkyYg&usqp=CAU",
        category: "SDE",
        role: "Ios Developer",
        company: "GlobalLogic Private Limited",
        location: "Noida",
        experience: "6+years",
    },
    {
        id: 4,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "WebDev",
        role: "MERN Developer",
        company: "GlobalLogic Private Limited",
        location:"Hyderabad",
        experience: "8+years",
    },
    {
        id: 5,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "SDE",
        role: "SDE-1",
        company: "Amazon",
        location:"Hyderabad",
        experience: "8+years",
    },
    {
        id: 6,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "SDE",
        role: "SDE-2",
        company: "Flipkart",
        location:"Hyderabad",
        experience: "8+years",
    },
    {
        id: 7,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "SDE",
        role: "SDE-2",
        company: "GlobalLogic Private Limited",
        location:"Hyderabad",
        experience: "8+years",
    },
    {
        id: 8,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "fullstack",
        role: "Java Full Stack Dev",
        company: "Oracle",
        location:"Hyderabad",
        experience: "8+years",
    },
    {
        id: 9,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "SDE",
        role: "SDE-2",
        company: "GlobalLogic Private Limited",
        location:"Hyderabad",
        experience: "8+years",
    },
    {
        id: 10,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "testing",
        role: "QA-Engineer",
        company: "HCL Technologies",
        location:"Hyderabad",
        experience: "8+years",
    },
    {
        id: 11,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "testing",
        role: "Test-Manager",
        company: "HCL Technologies",
        location:"Hyderabad",
        experience: "8+years",
    },
    {
        id: 11,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "testing",
        role: "Test-Engineer",
        company: "Wipro",
        location:"Disneyland :)",
        experience: "8+years",
    },
    {
        id: 12,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "testing",
        role: "Test-Analyst",
        company: "Wipro",
        location:"Bengaluru",
        experience: "5+years",
    },
    {
        id: 13,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "testing",
        role: "Test-Automation Engineer",
        company: "Zomato",
        location:"Haryana",
        experience: "5+years",
    },
    {
        id: 14,
        image: "https://miro.medium.com/max/1400/1*Y5S3wOm52_4iYusUagbEtw.jpeg",
        category: "ios",
        role: "Application Manager",
        company: "Apple Inc",
        location:"Bengaluru",
        experience: "5+years",
    },
    {
        id: 15,
        category: "ios",
        role: "Data-Access-Manager",
        company: "Apple Inc",
        location:"Haryana",
        experience: "5+years",
    },
    {
        id: 16,
        category: "ios",
        role: "Application Designer",
        company: "Apple Inc",
        location:"Haryana",
        experience: "5+years",
    },


]

export default jobListData;